; PlatformIO - STM32 Program 04-12 Combined

[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = arduino
upload_protocol = stlink
upload_flags =
	-c
	set CPUTAPID 0x2ba01477
monitor_speed = 115200